apiVersion: v1
kind: Service
metadata:
  name: notification-api
  namespace: itm-tickets
  labels:
    app: notification-api
spec:
  type: ClusterIP
  selector:
    app: notification-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
