apiVersion: v1
kind: Secret
metadata:
  name: itm-tickets-secrets
  namespace: itm-tickets
type: Opaque
stringData:
  postgres-connection: "Host=postgres.itm-tickets.svc.cluster.local;Database=itm_tickets;Username=itm_admin;Password=ChangeMe123!"
  rabbitmq-username: "itm_admin"
  rabbitmq-password: "ChangeMe123!"
  rabbitmq-connection: "amqp://itm_admin:ChangeMe123!@rabbitmq.itm-tickets.svc.cluster.local:5672"
  jwt-key: "SuperSecretKeyForITMTicketsGlobal2024!"
  redis-password: ""
