apiVersion: v1
kind: Service
metadata:
  name: inventory-api
  namespace: itm-tickets
  labels:
    app: inventory-api
spec:
  type: ClusterIP
  selector:
    app: inventory-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      appProtocol: http
    # Kubernetes (con HTTP/2 habilitado en Kestrel) ya soporta gRPC en el mismo puerto 8080.
